// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeSwitch: typeof import('E:/notes/blog/yangss/.vitepress/theme/components/DarkModeSwitch.vue')['default']
    'Eva:githubOutline': typeof import('~icons/eva/github-outline')['default']
    IconBtn: typeof import('E:/notes/blog/yangss/.vitepress/theme/components/IconBtn.vue')['default']
    'Ion:language': typeof import('~icons/ion/language')['default']
    Layout: typeof import('E:/notes/blog/yangss/.vitepress/theme/components/Layout.vue')['default']
    'Mdi:bookmarkOutline': typeof import('~icons/mdi/bookmark-outline')['default']
    ProjectCard: typeof import('E:/notes/blog/yangss/.vitepress/theme/components/ProjectCard.vue')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    TableOfContents: typeof import('E:/notes/blog/yangss/.vitepress/theme/components/TableOfContents.vue')['default']
  }
}

export { }
